# Copyright (c) 2026, Wellspring International School and contributors
# For license information, please see license.txt
"""Seed the configurable Knowledge Base from the legacy /docs content.

Reads ``knowledge_base_seed.json`` (generated by the frontend script
scripts/exportKnowledgeBaseSeed.mts — Markdown converted to HTML) and creates
SIS Knowledge Base Category + SIS Knowledge Base Article records, publishing an
initial live version for each. Idempotent: existing categories/articles (matched
by campus + code/slug) are skipped, so the patch is safe to re-run.
"""

import json
import os

import frappe

CATEGORY_DT = "SIS Knowledge Base Category"
ARTICLE_DT = "SIS Knowledge Base Article"


def _resolve_campus():
    campus = frappe.db.get_value("SIS Campus", {}, "name")
    return campus


def execute():
    seed_path = os.path.join(os.path.dirname(__file__), "knowledge_base_seed.json")
    if not os.path.exists(seed_path):
        frappe.logger().warning(f"[KB seed] seed file not found: {seed_path}")
        return

    with open(seed_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    campus_id = _resolve_campus()
    if not campus_id:
        frappe.logger().warning("[KB seed] no SIS Campus found; skipping")
        return

    code_to_name = {}

    # 1) Categories — top-level first, then children (so parent links resolve)
    categories = data.get("categories", [])
    ordered = [c for c in categories if not c.get("parent_code")] + [
        c for c in categories if c.get("parent_code")
    ]
    for cat in ordered:
        code = (cat.get("code") or "").strip().lower()
        if not code:
            continue
        existing = frappe.db.get_value(
            CATEGORY_DT, {"campus_id": campus_id, "code": code}, "name"
        )
        if existing:
            code_to_name[code] = existing
            continue
        parent_code = cat.get("parent_code")
        parent_name = code_to_name.get(parent_code) if parent_code else None
        doc = frappe.get_doc({
            "doctype": CATEGORY_DT,
            "campus_id": campus_id,
            "code": code,
            "title_vn": cat.get("title_vn") or code,
            "title_en": cat.get("title_en") or code,
            "parent_category": parent_name,
            "display_order": cat.get("display_order") or 0,
            "is_active": 1,
        })
        doc.insert(ignore_permissions=True)
        code_to_name[code] = doc.name

    # 2) Articles — create as draft, then publish the initial version
    created = 0
    for art in data.get("articles", []):
        category_code = (art.get("category_code") or "").strip().lower()
        slug = (art.get("slug") or "").strip().lower()
        category_name = code_to_name.get(category_code)
        if not category_name or not slug:
            frappe.logger().warning(
                f"[KB seed] skip article slug={slug} (category {category_code} unresolved)"
            )
            continue
        if frappe.db.exists(
            ARTICLE_DT,
            {"campus_id": campus_id, "category": category_name, "slug": slug},
        ):
            continue
        doc = frappe.get_doc({
            "doctype": ARTICLE_DT,
            "campus_id": campus_id,
            "category": category_name,
            "slug": slug,
            "title_vn": art.get("title_vn") or slug,
            "title_en": art.get("title_en") or slug,
            "summary_vn": art.get("summary_vn") or "",
            "summary_en": art.get("summary_en") or "",
            "content_vn": art.get("content_vn") or "",
            "content_en": art.get("content_en") or "",
            "display_order": art.get("display_order") or 0,
            "status": "draft",
        })
        doc.insert(ignore_permissions=True)
        doc.publish(note="Seed import từ /docs")
        created += 1

    frappe.db.commit()
    frappe.logger().info(
        f"[KB seed] done: {len(code_to_name)} categories, {created} new articles published"
    )
