name: CI - Code Quality & Testing

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pre-commit

      - name: Run pre-commit hooks
        run: |
          pre-commit install
          pre-commit run --all-files || true

      - name: Run Ruff Linter
        run: |
          ruff check erp/ --output-format=github

      - name: Run Ruff Formatter
        run: |
          ruff format erp/ --check

      - name: Check Python syntax
        run: |
          python -m py_compile erp/**/*.py || true

  validate-frappe-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Frappe App Structure
        run: |
          echo "🔍 Validating Frappe app structure..."

          # Kiểm tra các file bắt buộc
          required_files=(
            "erp/__init__.py"
            "erp/hooks.py"
            "erp/modules.txt"
            "pyproject.toml"
          )

          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            else
              echo "✅ Found: $file"
            fi
          done

          # Kiểm tra hooks.py có app_name
          if grep -q "app_name.*=.*\"erp\"" erp/hooks.py; then
            echo "✅ App name configured correctly"
          else
            echo "❌ App name not found in hooks.py"
            exit 1
          fi

          # Kiểm tra modules.txt
          if [ -s "erp/modules.txt" ]; then
            echo "✅ Modules file exists and not empty"
          else
            echo "❌ modules.txt is missing or empty"
            exit 1
          fi

          echo "✅ Frappe app structure validation passed!"

  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security scan
        run: |
          echo "🔒 Running security checks..."

          # Kiểm tra các file nhạy cảm không được commit
          sensitive_patterns=(
            "password"
            "secret"
            "api_key"
            "private_key"
            "*.pem"
            "*.key"
          )

          for pattern in "${sensitive_patterns[@]}"; do
            if find . -name "$pattern" -not -path "./.git/*" | grep -q .; then
              echo "⚠️ Warning: Found potentially sensitive files matching: $pattern"
            fi
          done

          # Kiểm tra hardcoded credentials trong code
          if grep -r -i "password.*=" erp/ --exclude-dir=.git || \
             grep -r -i "secret.*=" erp/ --exclude-dir=.git || \
             grep -r -i "api_key.*=" erp/ --exclude-dir=.git; then
            echo "⚠️ Warning: Found potential hardcoded credentials"
          else
            echo "✅ No hardcoded credentials found"
          fi

          echo "✅ Security scan completed!"
